problem:
  instance:
    H: 1
    G: 1
    P: 1
    C: 1
    K: 1
    
  shape:
    data-spaces:
    - name: Inputs
      projection:
      - - - H
      - - - P
      - - - C
    - name: Weights
      projection:
      - - - [H, G]
      - - - C
      - - - K
    - name: Outputs
      projection:
      - - - H
      - - - P
      - - - K
      read-write: true
    dimensions:
    - H
    - G
    - P
    - C
    - K
